export { default as BgImage } from 'components/Base/BgImage/BgImage'
export { default as Blocks } from 'components/Base/Blocks/Blocks'
export { default as Box } from 'components/Base/Box/Box'
export { default as Btn } from 'components/Base/Btn/Btn'
export { default as Col } from 'components/Base/Col/Col'
export { default as Container } from 'components/Base/Container/Container'
export { default as Hr } from 'components/Base/Hr/Hr'
export { default as HList } from 'components/Base/HList/HList'
export { default as Icon } from 'components/Base/Icon/Icon'
export { default as Img } from 'components/Base/Img/Img'
export { default as MaxWidth } from 'components/Base/MaxWidth/MaxWidth'
export { default as Row } from 'components/Base/Row/Row'
export { default as Tier } from 'components/Base/Tier/Tier'
export { default as Txt } from 'components/Base/Txt/Txt'

